name: Publish new Version
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - run: yarn lint
      - run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
