name: Publish new Version
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - run: yarn lint
      - run: yarn run typecheck
      - run: yarn run build:docs
      - run: yarn make
      - uses: 'paramsinghvc/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
