name: Verify
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - run: yarn run lint
      - run: yarn run typecheck
      - run: yarn run build:docs
      - run: yarn run make
      - uses: actions/upload-pages-artifact@v2
        id: artifact
        with:
          path: dist-docs
      - uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ steps.artifact.outputs.artifact_id }}
