name: Verify
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - run: yarn run lint
      - run: yarn run make
